### PR TITLE
chore: changed app icons to show barbeat logo

### PR DESCRIPTION
**Pull request by stefanomusicman**
# Description of the problem
configured setup to have app icons show barbeat logo instead of flutter logo

## How does it solve the problem
flutter logo has been replaced with flutter logo

# References (also the Jira ticket)
BAR-13

# Checklist:

- [ ] I re-reviewed the Jira ticket now to make sure 
- [ ] My code follows the style guidelines of this project & of Dart
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have wrote some documentation if I changed a big behavior of the code
- [ ] My changes generate no new warnings/and if they do, I described them to the team
- [ ] I have added tests that prove my fix is effective or that my feature works if I worked on a logic class/function
- [ ] New and existing unit and integration tests pass locally with my changes

### CODE REVIEW

**Comment by stefanomusicman** [comment]
it seems that the flutter_launcher_icons package only works with png images
i find the image starts to look a little pixelated when it's large

**Comment by stefanomusicman** [comment]
Untitled

**Comment by danielemonaca** [comment]
Yeah, you should import the starting `logo.png` in a bigger resolution, so that it could stretch it without having issues with it.

For now, I am just going to approve it and merge it to have as a temporary solution

**Review by danielemonaca — APPROVED** [review]
LGTM for temporary use

**Pull request merged**
