### PR TITLE
Feat.bar 88 - Search Screen 

### PR DESCRIPTION
**Pull request by danielemonaca**
# Description of the problem

image

@stefanomusicman All about the background + search bar is done, what is left to do is the actual search item design, for testing purposes, until we have all data, you can just have a few mock items

# References (also the Jira ticket)

https://unboolean.atlassian.net/jira/software/projects/BAR/boards/3?selectedIssue=BAR-88

# Checklist:

- [x] I re-reviewed the Jira ticket now to make sure 
- [x] My code follows the style guidelines of this project & of Dart
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have wrote some documentation if I changed a big behavior of the code
- [x] My changes generate no new warnings/and if they do, I described them to the team
- [ ] I have added tests that prove my fix is effective or that my feature works if I worked on a logic class/function
- [ ] New and existing unit and integration tests pass locally with my changes

### CODE REVIEW

**Comment by danielemonaca** [comment]
All yours @stefanomusicman :)

**Comment by stefanomusicman** [comment]
Untitled

**Comment by stefanomusicman** [comment]
Untitled

**Comment by danielemonaca** [comment]
Hey, the only thing missing are:

- the gradient linear is starting from the opposite side
- the gradient color(liquidColor for the background) should be wrapped inside the `lightenColor()` helper function that I made ( again, you can find inspiration in `details_main.dart` line 75

**Comment by stefanomusicman** [comment]
Latest changes with gradient direction changed and using the helper functions
Untitled

**Review by stefanomusicman — APPROVED** [review]

**Pull request merged**
